export const checkboxes = [
  {
    id: 0,
    key: 'business',
    label: 'Business Law',
    name: 'Business Law',
    property: 'column_1',
  },
  {
    id: 1,
    key: 'firmnews',
    label: 'Firm News',
    name: 'Firm News',
    property: 'column_1',
  },
  {
    id: 2,
    key: 'publiclaw',
    label: 'Government & Public Law',
    name: 'Government & Public Law',
    property: 'column_1',
  },
  {
    id: 3,
    key: 'technology',
    label: 'Technology',
    name: 'Technology',
    property: 'column_1',
  },
  {
    id: 4,
    key: 'tax',
    label: 'Tax',
    name: 'Tax',
    property: 'column_1',
  },
  {
    id: 5,
    key: 'firmevents',
    label: 'Firm Events',
    name: 'Firm Events',
    property: 'column_1',
  },
  {
    id: 14,
    key: 'cannabis',
    label: 'Cannabis Law',
    name: 'Cannabis Law',
    property: 'column_1',
  },
  {
    id: 6,
    key: 'commercialRealEstate',
    label: 'Commercial Real Estate',
    name: 'Commercial Real Estate',
    property: 'column_two',
  },
  {
    id: 7,
    key: 'covid19Alert',
    label: 'Covid-19 Alert',
    name: 'Covid-19 Alert',
    property: 'column_two',
  },
  {
    id: 8,
    key: 'cyberSecurityDataPrivacy',
    label: 'Cyber Security',
    name: 'Cyber Security',
    property: 'column_two',
  },
  {
    id: 9,
    key: 'entertainmentSports',
    label: 'Entertainment & Sports',
    name: 'Entertainment & Sports',
    property: 'column_two',
  },
  {
    id: 10,
    key: 'environmentalLaw',
    label: 'Environmental Law',
    name: 'Environmental Law',
    property: 'column_two',
  },
  {
    id: 11,
    key: 'intellectualProperty',
    label: 'Intellectual Property',
    name: 'Intellectual Property',
    property: 'column_two',
  },
  {
    id: 12,
    key: 'laboremployment',
    label: 'Labor Employment',
    name: 'Labor Employment',
    property: 'column_two',
  },
  {
    id: 13,
    key: 'litigation',
    label: 'Litigation',
    name: 'Litigation',
    property: 'column_two',
  },
];
